@echo off
set GIT_PATH="C:\Program Files\Git\cmd\git.exe"
echo [1/5] Initializing Git...
%GIT_PATH% init
echo [2/5] Adding files...
%GIT_PATH% add .
echo [3/5] Committing changes...
%GIT_PATH% commit -m "Fix structure and asset paths for GitHub Pages"
echo [4/5] Setting branch to main...
%GIT_PATH% branch -M main
echo [5/5] Pushing to GitHub...
%GIT_PATH% remote add origin https://github.com/Alaa20120/baseett.git
%GIT_PATH% push -u origin main -f
echo Done! If asked for a password, use your GitHub Personal Access Token.
pause
